### ISSUE TITLE
Encountering error

### ISSUE THREAD

**Issue by vibhavk** [EvilPort2/Face-Recognition#1]
Traceback (most recent call last):
  File "faceRecognizeMain.py", line 3, in <module>
    from py.recognize import faceRecognize
  File "/home/vibhav/Downloads/Face-Recognition-master/py/recognize.py", line 36
    cv2.rectangle(img, (x, y), (x + w, y + h), 2)
                                                ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by EvilPort2** [comment]
try replacing every tab with 4 spaces

**Comment by vibhavk** [comment]
Traceback (most recent call last):
  File "save_face.py", line 6, in <module>
    from imutils import face_utils
ModuleNotFoundError: No module named 'imutils'

**Comment by EvilPort2** [comment]
try pip install imutils in a terminal or command prompt

**Comment by atmecskrishna** [comment]
When running recognize.py getting this error
" _assert_warns = np.testing.assert_warns

AttributeError: module 'numpy' has no attribute 'testing'"
